### ISSUE TITLE
Hardening of resource-metadata lambda

### ISSUE THREAD

**Issue by dennischristmann** [coralogix/terraform-coralogix-aws#113]
On AWS, we are using AWS Control Tower / Landing Zone to manage a multi AWS account environment. By using Control Tower, multiple Lambda Functions are created in each account that is managed by AWS Control Tower. Those lambdas have very restrict service control policies, prohibiting most roles/users to read/describe the lambdas - actually the lambdas should be managed by the Organization account only.

The resource-metadata lambda stumbles on those lambdas and terminates with an Error (see below). In my opinion, the lambda should be hardened and skip those resources (with some log output with severity WARN), but should not fail completely in such a situation: 

```
ERROR	Invoke Error 	
{
    "errorType": "AccessDeniedException",
    "errorMessage": "User: arn:aws:sts::12345678900:assumed-role/Coralogix-resource-metadata-IXjzla5XZGnF-Role/Coralogix-resource-metadata-IXjzla5XZGnF is not authorized to perform: lambda:GetFunction on resource: arn:aws:lambda:eu-central-1:12345678900:function:srv-lz-create-123-xyz with an explicit deny in a service control policy",
    "name": "AccessDeniedException",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 403,
        "requestId": "2759b649-59a2-4153-bfca-9f101cd24418",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "message": "User: arn:aws:sts::12345678900:assumed-role/Coralogix-resource-metadata-IXjzla5XZGnF-Role/Coralogix-resource-metadata-IXjzla5XZGnF is not authorized to perform: lambda:GetFunction on resource: arn:aws:lambda:eu-central-1:12345678900:function:srv-lz-create-123-xyz with an explicit deny in a service control policy",
    "stack": [
        "AccessDeniedException: User: arn:aws:sts::12345678900:assumed-role/Coralogix-resource-metadata-IXjzla5XZGnF-Role/Coralogix-resource-metadata-IXjzla5XZGnF is not authorized to perform: lambda:GetFunction on resource: arn:aws:lambda:eu-central-1:12345678900:function:srv-lz-create-123-xyz with an explicit deny in a service control policy",
        "    at throwDefaultError (/var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)",
        "    at /var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39",
        "    at de_GetFunctionCommandError (/var/task/node_modules/@aws-sdk/client-lambda/dist-cjs/protocols/Aws_restJson1.js:2676:20)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20",
        "    at async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
        "    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26",
        "    at async file:///var/task/lambda.js:49:32",
        "    at async traverse (file:///var/task/common.js:32:22)"
    ]
}
```

**Comment by RafalSumislawski** [comment]
Hi @dennischristmann 
The fix is released in the latest version of the lambda. Let me know in case you run into any further issues.
